### ISSUE TITLE
datetime column in clean.gmex has error

### ISSUE THREAD

**Issue by JWMorley** [rBatt/trawlData#72]
Some rows for the 'datetime' column within clean.gmex are not created correctly from the 'date' column.
Example of a haul with an error:
`head(clean.gmex[station==170625 & CRUISE_NO==1001])`

**Comment by rBatt** [comment]
Odd b/c manually running code for that line produces correct `datetime` output. Hoping this is a simple matter of the data file needing to be updated (e.g., if last clean.gmex.RData file creation was after the update to the code). Otherwise, I'm not sure.

[gmex `datetime` created here](https://github.com/rBatt/trawlData/blob/master/R/clean.columns.R#L140)
[`getDate` function](https://github.com/rBatt/trawlData/blob/master/R/formatValue.R#L205)

**Comment by rBatt** [comment]
Doesn't work:
`getDate(c("8/1/08","11/1/07"))`
> `"2008-01-08 GMT" "2011-01-07 GMT"`


Does work:
`getDate(c("8/1/08","8/1/08"))` 
> `2008-08-01 GMT" "2008-08-01 GMT"`

**Comment by rBatt** [comment]
Switched the orders of the default `orders` argument. It now puts month-first formats first.

However, the `parse_date_time` documentation does not say anything about the order of characters in the `orders` argument affecting format selection. My guess is that this is just a side effect in the event of a tie-breaker.

The new function is

```{r}
getDate <-  function(x, orders, year=1957, tz="GMT", ...){
	requireNamespace("lubridate", quietly=TRUE)
	year <- as.integer(year)
	stopifnot(nchar(year) == 4L)
	if(missing(orders)){
		# orders <- paste0(rep(c("ymd", "mdy", "Ymd", "mdY"),each=5), c(" HMS"," HM", " H", "M", ""))
		orders <- paste0(rep(c("mdy", "mdY", "ymd", "Ymd"),each=5), c(" HMS"," HM", " H", "M", ""))
	}
	
	x <- lubridate::parse_date_time(x, orders=orders, tz=tz, ...)
	yx <- lubridate::year(x)
	# yxl <- yx < 100
	# if(any(yxl)){
	#   m <- yx[yxl]
	# 	lubridate::year(x)[yxl] <- ifelse(m >= year %% 100, 1900+m, 2000+m)
	# }
	m <- yx %% 100
	lubridate::year(x) <- ifelse(m > year %% 100, 1900+m, 2000+m)
  x
}
```

I don't know if this solves the problem for all regions, or not.
